// getproduct
export const GET_PRODUCT_INIT = "GET_PRODUCT_INIT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";


// getsingel
export const GET_SINGEL_INIT = "GET_SINGEL_INIT";
export const GET_SINGEL_SUCCESS = "GET_SINGEL_SUCCESS";
export const GET_SINGEL_FAIL = "GET_SINGEL_FAIL";
